// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCElkeq9GQhRI1tKVwfs7_WZt1VgqGmmk',
    appId: '1:267481772614:web:f9cb672ff46da7ab0d9047',
    messagingSenderId: '267481772614',
    projectId: 'camp-sugar-manager',
    authDomain: 'camp-sugar-manager.firebaseapp.com',
    storageBucket: 'camp-sugar-manager.firebasestorage.app',
    measurementId: 'G-21LWTBM7J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWoZXjfgPj4nZZpnZI0fSsDUrObjzAGg8',
    appId: '1:267481772614:android:a54ead80fcbc297b0d9047',
    messagingSenderId: '267481772614',
    projectId: 'camp-sugar-manager',
    storageBucket: 'camp-sugar-manager.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaK9RwJW3olOVNtcx8ROSqPFnf6DpdUjM',
    appId: '1:267481772614:ios:52d31d9815643e050d9047',
    messagingSenderId: '267481772614',
    projectId: 'camp-sugar-manager',
    storageBucket: 'camp-sugar-manager.firebasestorage.app',
    iosBundleId: 'com.example.campSugarManager',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaK9RwJW3olOVNtcx8ROSqPFnf6DpdUjM',
    appId: '1:267481772614:ios:52d31d9815643e050d9047',
    messagingSenderId: '267481772614',
    projectId: 'camp-sugar-manager',
    storageBucket: 'camp-sugar-manager.firebasestorage.app',
    iosBundleId: 'com.example.campSugarManager',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3Z-MrTrc57xL0ofrXtu2u9Q7u8cQkXbE',
    appId: '1:397620043905:web:6bcc5bdcf159fc84fdad80',
    messagingSenderId: '397620043905',
    projectId: 'tennis-club-app-fb311',
    authDomain: 'tennis-club-app-fb311.firebaseapp.com',
    databaseURL: 'https://tennis-club-app-fb311-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tennis-club-app-fb311.firebasestorage.app',
    measurementId: 'G-P8T24YE7FQ',
  );
}
